# Generated by Django 6.0.4 on 2026-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('db_type', models.CharField(default='sqlite', max_length=20)),
                ('host', models.CharField(blank=True, max_length=200, null=True)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('database_name', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_connections',
            },
        ),
        migrations.DeleteModel(
            name='MyTable',
        ),
    ]
