# Generated by Django 6.0.4 on 2026-04-27 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_interface', '0002_databaseconnection_delete_mytable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_databases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('host', models.CharField(default='localhost', max_length=200)),
                ('port', models.IntegerField(default=5432)),
                ('username', models.CharField(default='postgres', max_length=100)),
                ('password', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'db_servers',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='DatabaseConnection',
        ),
        migrations.AddField(
            model_name='database',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='databases', to='db_interface.databaseserver'),
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together={('server', 'name')},
        ),
    ]
